### PR TITLE
Fix visualizer constantly giving internet connection error

### PR DESCRIPTION
**Pull request by GGshor**
The `getAudioData` function from Spicetify doesn't work anymore, so as a temporary workaround, I changed it to use the normal API from spotify to get the analyzer data.

### CODE REVIEW

**Comment by pragit-raj-sharma** [comment]
how can I test this.

**Comment by GGshor** [comment]
> how can I test this.

You can install it the same way you do with the normal repo [README](https://github.com/Konsl/spicetify-ncs-visualizer/blob/main/README.md), but the only you difference is that you download the dist from my repo. https://github.com/GGshor/spicetify-ncs-visualizer/tree/dist

**Comment by pragit-raj-sharma** [comment]
> > how can I test this.
> 
> You can install it the same way you do with the normal repo [README](https://github.com/Konsl/spicetify-ncs-visualizer/blob/main/README.md), but the only you difference is that you download the dist from my repo. https://github.com/GGshor/spicetify-ncs-visualizer/tree/dist

Thanks, I was looking for it but there was no commit in the dist branch at that time.

**Comment by GGshor** [comment]
> > > how can I test this.
> > 
> > 
> > You can install it the same way you do with the normal repo [README](https://github.com/Konsl/spicetify-ncs-visualizer/blob/main/README.md), but the only you difference is that you download the dist from my repo. https://github.com/GGshor/spicetify-ncs-visualizer/tree/dist
> 
> Thanks, I was looking for it but there was no commit in the dist branch at that time.

Yeah no worries, once you said it I bumped the branch on my repo.

**Comment by ElTarquin** [comment]
image

**Comment by GGshor** [comment]
> image
> 
> 

Please try removing the app and then adding it back again by running these commands in the terminal:

To remove the app use these commands in order:
`spicetify config custom_apps ncs-visualizer-`
`spicetify apply`

And then adding it back:
`spicetify config custom_apps ncs-visualizer`
`spicetify apply`

**Comment by GGshor** [comment]
Closed PR as it has been already resolved by commit aae57b502e0a6da513cbb70214dabf911fcd6d74

**Pull request closed without merging**
